apiVersion: v1                  #‚û°Ô∏è Uses the core Kubernetes API group (v1) for basic objects like ConfigMap.
kind: ConfigMap                 #‚û°Ô∏è Creates a ConfigMap object. |üëâ Used to store non-sensitive configuration data.
metadata:                       
  name: mysql-configmaps        #‚û°Ô∏è Name of the ConfigMap is mysql-configmaps.| You will reference this name inside Pods or Deployments.
  labels:                       #
     app: mysql-configmaps      #‚û°Ô∏è Labels used for organizing the ConfigMap (not mandatory, but good practice).
data:                           
  mysqlkey: "1234"              #‚û°Ô∏è Stores key-value pairs.
